# MyHomeworkSpace configuration
[server]
Port = 3010
APIURLBase = "http://api-v2.myhomework.invalid/"
AppURLBase = "http://app.myhomework.invalid/#!"
ReverseProxyHeader = ""
HostName = "local"

[database]
Host = "localhost"
Username = "myhomeworkspace"
Password = "myhomeworkspace"
Database = "myhomeworkspace"

[email]
Enabled = true
FromAddress = "misconfigured@myhomework.invalid"
FromDisplay = "MyHomeworkSpace Codespace <misconfigured@myhomework.invalid>"
SMTPHost = "localhost"
SMTPPort = 1025
SMTPSecure = false
SMTPUsername = "accounts@myhomework.space"
SMTPPassword = "password123"

[redis]
Host = "localhost"
Port = 6379

[cors]
Enabled = false
Origins = [ "https://app.myhomework.invalid", "https://myhomework.invalid" ]

[errorlog]
SlackEnabled = false
SlackURL = ""

[feedback]
SlackEnabled = false
SlackURL = ""

[tasks.slack]
SlackEnabled = false
SlackURL = ""
SlackLogEnabled = false
SlackLogURL = ""

[mit]
AuthProxyURL = ""
DataProxyURL = ""
ProxyToken = ""