version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    volumes:
      - ..:/go

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myhomeworkspace
      MYSQL_USER: myhomeworkspace
      MYSQL_PASSWORD: myhomeworkspace
    network_mode: service:app

  redis:
    image: redis
    network_mode: service:app

  mailhog:
    image: mailhog/mailhog
    network_mode: service:app

volumes:
  mysql-data:
  redis-data:
